In [1]:
import torch
print(torch.__version__)

2.7.0+cpu


vectors

In [ ]:
import torch
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)   # number of sqr brackets
print(vector.shape)  #number or elements


tensor([7, 7])
1
torch.Size([2])


MATRIX

In [ ]:
MATRIX = torch.tensor([[2,6],[5,9],[1,2]])
MATRIX

tensor([[2, 6],
        [5, 9],
        [1, 2]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([2, 6])

In [ ]:
MATRIX[1]

tensor([5, 9])

In [ ]:
MATRIX[2]

tensor([1, 2])

In [ ]:
MATRIX.shape

torch.Size([3, 2])

tensor

In [ ]:
tensor = torch.tensor([[[[3,6,9],[2,4,6],[1,5,10]],[[3,6,9],[2,4,6],[1,5,10]]]])
tensor.ndim

4

In [ ]:
tensor.shape

torch.Size([1, 2, 3, 3])

In [ ]:
tensor[0]

tensor([[[ 3,  6,  9],
         [ 2,  4,  6],
         [ 1,  5, 10]],

        [[ 3,  6,  9],
         [ 2,  4,  6],
         [ 1,  5, 10]]])

### random tensor

In [ ]:
rand_tensor = torch.rand(3,5,4)
rand_tensor

tensor([[[0.6310, 0.9455, 0.3536, 0.4075],
         [0.2989, 0.7122, 0.0046, 0.7453],
         [0.8887, 0.5564, 0.8292, 0.6433],
         [0.5648, 0.2389, 0.8165, 0.4228],
         [0.3623, 0.3858, 0.9225, 0.1222]],

        [[0.9484, 0.6789, 0.3942, 0.4592],
         [0.9674, 0.4245, 0.3177, 0.1068],
         [0.9107, 0.9340, 0.8840, 0.6455],
         [0.4869, 0.1194, 0.4196, 0.8972],
         [0.2970, 0.4865, 0.4043, 0.8803]],

        [[0.7266, 0.7652, 0.5685, 0.0866],
         [0.4474, 0.4306, 0.8297, 0.0186],
         [0.0404, 0.5497, 0.5924, 0.9025],
         [0.4809, 0.3393, 0.5084, 0.6621],
         [0.6433, 0.4102, 0.1372, 0.8799]]])

In [ ]:
rand_tensor.shape,rand_tensor.ndim

(torch.Size([3, 5, 4]), 3)

zeros and ones

In [ ]:
zeros =torch.zeros(3,5,4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
zeros*rand_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(1,2,3)
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

creating a range of tensors and tensor-like





In [ ]:
range_tensor = torch.arange(0,55,5)     #(start,end,step)
range_tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
#creating tensorlike
tensor_like = torch.zeros_like(input= range_tensor)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##tensor datatypes


In [ ]:
default_tensor = torch.tensor(
    [54.4,0.2,4.7],
    dtype = None,   #what dtype is the tensor
    device = None,  #what device your tensor stored
    requires_grad = False   #whether or not to track gradient
)
default_tensor.dtype

torch.float32

changing to lesser dtype helps in faster execution (eg:float16) similarly changin to grater dtype help storing precise info about the tensor (eg:float64) these are basically how much space given to the tensor

In [ ]:
altering_dtype_tensor = default_tensor.type(torch.float16)
altering_dtype_tensor.dtype

torch.float16

###getting information from tensors

In [ ]:
some_tensor = torch.rand(5,3)
some_tensor

tensor([[0.9551, 0.3675, 0.7395],
        [0.6030, 0.6745, 0.4783],
        [0.5724, 0.0198, 0.8209],
        [0.5387, 0.9339, 0.4456],
        [0.8614, 0.6679, 0.3562]])

In [ ]:
some_tensor_2 = some_tensor.type(torch.float16)

In [ ]:
print(f"dtype of tensor:{some_tensor_2.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device of tensor:{some_tensor.device}")

dtype of tensor:torch.float16
shape of tensor:torch.Size([5, 3])
device of tensor:cpu


## manipulating tensor



*   addition
*   subtraction
*   multiplication
*   division
*   matrix multiplication





In [ ]:
tensor = torch.tensor([3,6,9])
tensor

tensor([3, 6, 9])

In [ ]:
tensor + 10

tensor([13, 16, 19])

In [ ]:
tensor *5

tensor([15, 30, 45])

In [ ]:
tensor -2

tensor([1, 4, 7])

In [ ]:
tensor /3

tensor([1., 2., 3.])

another way

In [ ]:
torch.add(tensor, 10)  #simiraly rest of the operation can also be done like this but previous one is simpler and easy

tensor([13, 16, 19])

###matrix multiplication (two ways)

*   element wise multiplication
*   matix multiplication



In [ ]:
#element wise
print(tensor,"*",tensor)
print(f"equals:{tensor*tensor}")

tensor([3, 6, 9]) * tensor([3, 6, 9])
equals:tensor([ 9, 36, 81])


sometimes using func like matmul() is better than traditional symbol way like below



In [ ]:
#matrix multiplication
%%time
torch.matmul(tensor,tensor)


CPU times: user 770 µs, sys: 46 µs, total: 816 µs
Wall time: 626 µs


tensor(126)

In [ ]:
#altering way to do matrix multiplication simple but not explainatory
%%time
tensor @ tensor

CPU times: user 592 µs, sys: 0 ns, total: 592 µs
Wall time: 438 µs


tensor(126)

###Matrix multiplication two main rules which will prevent shape errors.

1. The inner dimensions must match:

(3, 2) @ (3, 2) won’t work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) → (2, 2)

(3, 2) @ (2, 3) → (3, 3)


In [ ]:
torch.rand(2,5)

tensor([[0.3583, 0.9505, 0.9387, 0.6479, 0.3699],
        [0.0840, 0.7379, 0.1364, 0.4996, 0.3776]])

In [ ]:
tensor = torch.rand(2,5)@torch.rand(5,2)
tensor

tensor([[1.5155, 0.8502],
        [3.3398, 1.8338]])

In [ ]:
tensor.shape

torch.Size([2, 2])

When we have two tensors in the same shape but we need to do matrix multiplication means it does not follow the rules to do matrix multiplication. In that case we use transpose. We transpose one of the tensor and then do matrix multiplication then it will work.

In [ ]:
tensor_a = torch.tensor([[2,4],
                        [4,7],
                        [5,3]])
tensor_b = torch.tensor([[4,6],
                        [3,7],
                        [2,4]])


ttensor = tensor_a@tensor_b.T
ttensor,ttensor.shape

(tensor([[32, 34, 20],
         [58, 61, 36],
         [38, 36, 22]]),
 torch.Size([3, 3]))

tensor aggregation(min,max,mean,sum)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())     #for finding mean tensor has to be either float or complex value
print(x.sum())

tensor(0)
tensor(90)
tensor(45.)
tensor(450)


finding positional min max

In [ ]:
x = torch.arange(1,100,5)


In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(19)

In [ ]:
x[19]

tensor(96)

###Reshaping, stacking, squeezing, and unsqueezing tensors.


*   Reshaping- Reshapes an input tensor to a defined shape,
*  view- to return a view of an input tensor of certain shape but keeps the same memory as the original tensor.
* Stacking- Combines multiple tensors on top of each other(vstack) or side-by-side (hstack).
* Squeeze- Removes all one dimensions from a tensor.
* Unsqueeze- Add a one dimension to a target tensor.
*  Permute- Return a view of the input with dimensions permuted, swapped in a certain way.




In [ ]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

the reshaping value must be compatible, like when the shape of the tensor is like 9, it has to be multiplied, the reshaping value has to be multiplied like 3 into 3,1 into 9 or 9 into 1. If we are not giving a compatible values, then it won't work.

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# changing the view
z = x.view(1,9)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x(because a view of a tensor shares a same memory as the original tensor)
z[:,3] = 8
x,z

(tensor([1., 2., 3., 8., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 8., 5., 6., 7., 8., 9.]]))

##stacking
stacking can be done in three diff ways

In [ ]:
#1
x_stacked = torch.vstack((x,x,x,x))    #vertical stack
x_stacked


tensor([[1., 2., 3., 8., 5., 6., 7., 8., 9.],
        [1., 2., 3., 8., 5., 6., 7., 8., 9.],
        [1., 2., 3., 8., 5., 6., 7., 8., 9.],
        [1., 2., 3., 8., 5., 6., 7., 8., 9.]])

OR

In [ ]:
x_stacked = torch.stack((x,x,x,x),dim=0)
x_stacked

tensor([[1., 2., 3., 8., 5., 6., 7., 8., 9.],
        [1., 2., 3., 8., 5., 6., 7., 8., 9.],
        [1., 2., 3., 8., 5., 6., 7., 8., 9.],
        [1., 2., 3., 8., 5., 6., 7., 8., 9.]])

In [ ]:
#2
x_stacked = torch.stack((x,x,x,x),dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [8., 8., 8., 8.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
#3
x_stacked = torch.hstack((x,x,x,x))        #horizontal stack
x_stacked

tensor([1., 2., 3., 8., 5., 6., 7., 8., 9., 1., 2., 3., 8., 5., 6., 7., 8., 9.,
        1., 2., 3., 8., 5., 6., 7., 8., 9., 1., 2., 3., 8., 5., 6., 7., 8., 9.])

###squeezing and unsqueezing

In [ ]:
#squeezing
print(f"previous tensor:{x_reshaped}")
print(f"previous shape:{x_reshaped.shape}")

#remove 1 dimension tensor
x_squeezed = x.squeeze()

print(f"\nnew tensor:{x_squeezed}")
print(f"new shape:{x_squeezed.shape}")

previous tensor:tensor([[1., 2., 3., 8., 5., 6., 7., 8., 9.]])
previous shape:torch.Size([1, 9])

new tensor:tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
new shape:torch.Size([9])


In [ ]:
#unsqueezing
print(f"previous tensor:{x_squeezed}")
print(f"previous shape:{x_squeezed.shape}")

#add an extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nnew tensor:{x_unsqueezed}")
print(f"new shape:{x_unsqueezed.shape}")


previous tensor:tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
previous shape:torch.Size([9])

new tensor:tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
new shape:torch.Size([1, 9])


permuting (rearranging)

In [ ]:
x_og = torch.rand(size=(224,224,3))
x_permuted = x_og.permute(2,0,1)

print(f"previous order:{x_og.shape}")
print(f"permuted:{x_permuted.shape}")

previous order:torch.Size([224, 224, 3])
permuted:torch.Size([3, 224, 224])


In [ ]:
x_og[0,0,0] = 61

In [ ]:
x_og

tensor([[[0.6005, 0.1405, 0.0076],
         [0.0558, 0.6204, 0.2616],
         [0.3711, 0.3398, 0.1509],
         ...,
         [0.7121, 0.5200, 0.2083],
         [0.1704, 0.9393, 0.4411],
         [0.1043, 0.4719, 0.2238]],

        [[0.6066, 0.1820, 0.8960],
         [0.6260, 0.0536, 0.6231],
         [0.1438, 0.2343, 0.3974],
         ...,
         [0.5976, 0.4256, 0.1489],
         [0.9248, 0.9993, 0.2347],
         [0.8862, 0.0195, 0.4203]],

        [[0.4987, 0.8289, 0.2520],
         [0.9503, 0.6388, 0.2127],
         [0.7478, 0.5142, 0.4260],
         ...,
         [0.9535, 0.4724, 0.3785],
         [0.1813, 0.1095, 0.1138],
         [0.9159, 0.0083, 0.3842]],

        ...,

        [[0.5970, 0.9470, 0.4177],
         [0.5669, 0.6160, 0.2044],
         [0.9670, 0.6903, 0.1706],
         ...,
         [0.6584, 0.0131, 0.4842],
         [0.1633, 0.9291, 0.2199],
         [0.6832, 0.0072, 0.8558]],

        [[0.4119, 0.0476, 0.7993],
         [0.1851, 0.9245, 0.4889],
         [0.

##indexing
similar to indexing in numpy

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[0,2,2]

tensor(9)

indexin with the semicolon which gives all values

In [ ]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,:,[[2],[2]]]

tensor([[[[3],
          [3]],

         [[6],
          [6]],

         [[9],
          [9]]]])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

##numpy to tensor

remember numpy and pytorch has different dtypes numpy-float64,pytorch-float32
it need to be considerd when workin with em

In [ ]:
import torch
import numpy as np

array = np.arange(1.0,9.0)
tensor = torch.from_numpy(array)
array,tensor,tensor.type         #here the dtype of tensor is converted to float 64 because it is converted into numpy

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 <function Tensor.type>)

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor = torch.ones(7)
tensor.dtype

torch.float32

##reproduciblity

 when we use a random values we use a random seed to flavor the randomness
 which gives reproduciblity (able to use again and again and again)

In [ ]:
tensor_a = torch.rand(3,4)
tensor_b = torch.rand(3,4)

print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)

tensor([[0.7481, 0.5889, 0.0984, 0.4177],
        [0.1266, 0.7554, 0.0423, 0.3648],
        [0.9060, 0.9472, 0.8014, 0.6362]])
tensor([[0.4426, 0.0458, 0.0150, 0.6894],
        [0.1763, 0.8346, 0.1489, 0.1436],
        [0.4335, 0.3739, 0.1739, 0.3500]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#now using random seed method
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
tensor_d = torch.rand(3,4)

print(tensor_c)
print(tensor_d)
print(tensor_c == tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


learn more about in random seed in wikipedia

###setting up GPU

In [ ]:
torch.cuda.is_available()

False

when you usin new device check for gpu with the below code:

 {device = 'cuda' if cuda.is_available else 'cpu'

 device}